# -*- coding: utf-8 -*-
"""final exam anual

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YnTpDHKBB2PvilPIkVz_RZ7gGNn1Yozt
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree
data=load_iris()
data
x=data.data
y=data.target
df=pd.DataFrame(x,columns=data.feature_names)
df
df['species']=pd.Categorical.from_codes(y,data.target_names)
print(df['species'].head())
print(df.describe())
print(df.info())
print(df['species'].value_counts())
X_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)
clf=DecisionTreeClassifier(random_state=4)
clf.fit(X_train,y_train)
y_pred=clf.predict(x_test)
plt.figure(figsize=(20,10))
tree.plot_tree(clf,filled=True, feature_names=data.feature_names,class_names=data.target_names)
plt.title('decision tree visualization ')
plt.show()
accuracy=accuracy_score(y_test,y_pred)
print('accuracy of the Decision tree model:',accuracy)